server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
     
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: admin@123
    

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 189973739195-eb5vlutn2fhohj30jt54v6p3drjb7tkg.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 1020445878801732
            client-secret: f4957ad2225cd13f864874f8e657da80
            scope:
            - email
            - public_profile
            
          naver:
            client-id: NYq8l1CP4LVBScv9mx92
            client-secret: HnqO9DUESL
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
                
           
            
            
      
  

